#!/usr/local/bin/bash

# Configuration jdk
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
export PATH="$JAVA_HOME/bin:$PATH"

# Configuration Maven
export MAVEN_HOME="/usr/local/Cellar/maven/3.3.3/libexec/"
export PATH="$MAVEN_HOME/bin:$PATH"

# Configuraton Jacorb
export JACORB_HOME="$PWD/vendor/jacorb-3.6.1"
export PATH="$JACORB_HOME/bin:$PATH"

# Jacorb configuration files
export JACORB_CONFIGS_PATH="$PWD/config"

# Configuration classpath
export CLASSPATH="."
export CLASSPATH="$JACORB_CONFIGS_PATH:$CLASSPATH"

# Remplace des configurations utilisateurs par les configurations du projet
mvn -gs ./scripts/settings.xml -v
